name: Sync on DOM Cloud
'on':
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke SGA deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_SGA }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_SGA }}
          data: >-
            {"commands":["git pull","npm i","npm test","sudo systemctl restart bridge"]}
      - name: Invoke NYC deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_NYC }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_NYC }}
          data: >-
            {"commands":["git pull","npm i","npm test","sudo systemctl restart bridge"]}
      - name: Invoke AMS deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_AMS }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_AMS }}
          data: >-
            {"commands":["git pull","npm i","npm test","sudo systemctl restart bridge"]}
      - name: Invoke TYO deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_TYO }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_TYO }}
          data: >-
            {"commands":["git pull","npm i","npm test","sudo systemctl restart bridge"]}
      - name: Invoke BLR deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_BLR }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_BLR }}
          data: >-
            {"commands":["git pull","npm i","npm test","sudo systemctl restart bridge"]}
      - name: Invoke SAO deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET_SAO }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH_SAO }}
          data: >-
            {"commands":["git pull","npm i","npm test","sudo systemctl restart bridge"]}